/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

import javax.swing.JOptionPane;


/**
 *
 * @author gpont
 */
public class Cadastro extends javax.swing.JFrame {

    

    /**
     * Creates new form NewJFrame
     */
    public Cadastro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Painel_principal = new javax.swing.JPanel();
        Painel_secundario = new javax.swing.JPanel();
        btClose = new javax.swing.JButton();
        Usuario_text = new javax.swing.JLabel();
        Senha_text = new javax.swing.JLabel();
        espaco_Senha = new javax.swing.JPasswordField();
        Usuario_espaco = new javax.swing.JTextField();
        senha_checkbox = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        btCadastro = new javax.swing.JToggleButton();
        Email_espaco = new javax.swing.JTextField();
        email_text = new javax.swing.JLabel();
        freelancer_chekbox = new javax.swing.JCheckBox();
        freelancer_chekbox2 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);
        setResizable(false);

        Painel_principal.setBackground(new java.awt.Color(204, 204, 204));

        Painel_secundario.setBackground(new java.awt.Color(153, 153, 153));

        btClose.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        btClose.setForeground(new java.awt.Color(255, 0, 51));
        btClose.setText("X");
        btClose.setBorder(null);
        btClose.setContentAreaFilled(false);
        btClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Painel_secundarioLayout = new javax.swing.GroupLayout(Painel_secundario);
        Painel_secundario.setLayout(Painel_secundarioLayout);
        Painel_secundarioLayout.setHorizontalGroup(
            Painel_secundarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Painel_secundarioLayout.createSequentialGroup()
                .addGap(0, 243, Short.MAX_VALUE)
                .addComponent(btClose, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        Painel_secundarioLayout.setVerticalGroup(
            Painel_secundarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel_secundarioLayout.createSequentialGroup()
                .addComponent(btClose)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Usuario_text.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Usuario_text.setText("Nome");

        Senha_text.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Senha_text.setText("Senha");

        espaco_Senha.setBackground(new java.awt.Color(153, 153, 153));
        espaco_Senha.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        espaco_Senha.setActionCommand("<Not Set>");
        espaco_Senha.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        espaco_Senha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                espaco_SenhaActionPerformed(evt);
            }
        });

        Usuario_espaco.setBackground(new java.awt.Color(153, 153, 153));
        Usuario_espaco.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Usuario_espaco.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        Usuario_espaco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Usuario_espacoActionPerformed(evt);
            }
        });

        senha_checkbox.setBackground(new java.awt.Color(204, 204, 204));
        senha_checkbox.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        senha_checkbox.setText(" Mostrar a senha");
        senha_checkbox.setToolTipText("");
        senha_checkbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                senha_checkboxActionPerformed(evt);
            }
        });

        jLabel2.setText("saintlance 1.0");

        btCadastro.setBackground(new java.awt.Color(255, 0, 51));
        btCadastro.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        btCadastro.setText("Cadastrar");
        btCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastroActionPerformed(evt);
            }
        });

        Email_espaco.setBackground(new java.awt.Color(153, 153, 153));
        Email_espaco.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Email_espaco.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        Email_espaco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Email_espacoActionPerformed(evt);
            }
        });

        email_text.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        email_text.setText("Email");

        freelancer_chekbox.setBackground(new java.awt.Color(204, 204, 204));
        freelancer_chekbox.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        freelancer_chekbox.setText("Desejo ser um freelancer");
        freelancer_chekbox.setToolTipText("");
        freelancer_chekbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                freelancer_chekboxActionPerformed(evt);
            }
        });

        freelancer_chekbox2.setBackground(new java.awt.Color(204, 204, 204));
        freelancer_chekbox2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        freelancer_chekbox2.setToolTipText("");
        freelancer_chekbox2.setBorder(null);
        freelancer_chekbox2.setContentAreaFilled(false);
        freelancer_chekbox2.setEnabled(false);
        freelancer_chekbox2.setFocusPainted(false);
        freelancer_chekbox2.setFocusable(false);
        freelancer_chekbox2.setRequestFocusEnabled(false);
        freelancer_chekbox2.setVerifyInputWhenFocusTarget(false);
        freelancer_chekbox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                freelancer_chekbox2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Painel_principalLayout = new javax.swing.GroupLayout(Painel_principal);
        Painel_principal.setLayout(Painel_principalLayout);
        Painel_principalLayout.setHorizontalGroup(
            Painel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel_principalLayout.createSequentialGroup()
                .addGroup(Painel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Painel_principalLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(Painel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(senha_checkbox, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(espaco_Senha, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Senha_text, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Usuario_text)
                            .addComponent(Usuario_espaco, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Email_espaco, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(email_text)
                            .addComponent(btCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(freelancer_chekbox)))
                    .addGroup(Painel_principalLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(freelancer_chekbox2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 137, Short.MAX_VALUE)
                .addComponent(Painel_secundario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        Painel_principalLayout.setVerticalGroup(
            Painel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Painel_secundario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(Painel_principalLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(email_text)
                .addGap(18, 18, 18)
                .addComponent(Email_espaco, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Usuario_text)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Usuario_espaco, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Senha_text, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(espaco_Senha, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(senha_checkbox, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(freelancer_chekbox, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btCadastro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addGroup(Painel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(freelancer_chekbox2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Painel_principal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Painel_principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(688, 547));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void espaco_SenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_espaco_SenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_espaco_SenhaActionPerformed

    private void senha_checkboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_senha_checkboxActionPerformed
           // TODO add your handling code here:
    if(senha_checkbox.isSelected()){
            espaco_Senha.setEchoChar((char)0);
        }else{
            espaco_Senha.setEchoChar('*');
        }     
    }//GEN-LAST:event_senha_checkboxActionPerformed

    private void btCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCloseActionPerformed
        // TODO add your handling code here:
        dispose();
        
    }//GEN-LAST:event_btCloseActionPerformed

    private void Usuario_espacoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Usuario_espacoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Usuario_espacoActionPerformed

    private void btCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastroActionPerformed
        // TODO add your handling code here:
       String email = Email_espaco.getText();
       String nome = Usuario_espaco.getText();
       String senha = String.valueOf(espaco_Senha.getPassword());
       // Verificar se os campos não estão vazios
       if(nome.isEmpty()||email.isEmpty() || senha.isEmpty()) {
           JOptionPane.showMessageDialog(this, "Por favor, preencha todos os campos.");
           return;
       }

       // Criar uma instância do LoginDAO
       dao.LoginDAO loginDAO = new dao.LoginDAO();
   
       beans.Usuario usuario = loginDAO.cadastro(nome, email, senha); // Passa o valor freelancer
   
       // Verificar se o cadastro foi bem-sucedido
       if (usuario != null) {
           // Sucesso no cadastro
           JOptionPane.showMessageDialog(this, "Cadastro bem-sucedido! Bem-vindo, " + usuario.getNome());
       
           Main prin = new Main();
           this.dispose();  // Fecha a tela de cadastro
           prin.setVisible(true);  // Abre a próxima tela
       
       } else {
           // Falha no cadastro
           JOptionPane.showMessageDialog(this, "Erro no cadastro. Tente novamente.");
       }
    }//GEN-LAST:event_btCadastroActionPerformed

    private void Email_espacoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Email_espacoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Email_espacoActionPerformed

    private void freelancer_chekboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_freelancer_chekboxActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_freelancer_chekboxActionPerformed

    private void freelancer_chekbox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_freelancer_chekbox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_freelancer_chekbox2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Email_espaco;
    private javax.swing.JPanel Painel_principal;
    private javax.swing.JPanel Painel_secundario;
    private javax.swing.JLabel Senha_text;
    private javax.swing.JTextField Usuario_espaco;
    private javax.swing.JLabel Usuario_text;
    private javax.swing.JToggleButton btCadastro;
    private javax.swing.JButton btClose;
    private javax.swing.JLabel email_text;
    private javax.swing.JPasswordField espaco_Senha;
    private javax.swing.JCheckBox freelancer_chekbox;
    private javax.swing.JCheckBox freelancer_chekbox2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JCheckBox senha_checkbox;
    // End of variables declaration//GEN-END:variables
}
