/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import beans.Freelancer;
import dao.FreelancerDAO;

/**
 *
 * @author guilherme.pcampos3
 */
public class freelancerview extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public freelancerview() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btClose = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnCriar = new javax.swing.JButton();
        btnAtualizar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        txtIDPesquisar = new javax.swing.JTextField();
        txtusuario = new javax.swing.JTextField();
        txtProfissao = new javax.swing.JTextField();
        btnEncontrar = new javax.swing.JButton();
        btnRelatorio = new javax.swing.JButton();
        txtHabilidade = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Barrademenu = new javax.swing.JMenuBar();
        Tela_inicial_menu = new javax.swing.JMenu();
        Projetos_menu = new javax.swing.JMenu();
        CriarProjetos = new javax.swing.JMenu();
        Freelancers_menu = new javax.swing.JMenu();
        criarPerfil = new javax.swing.JMenuItem();
        Perfil_menu = new javax.swing.JMenu();
        Ajuda_menu = new javax.swing.JMenu();
        Admin_login = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        btClose.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        btClose.setForeground(new java.awt.Color(255, 0, 51));
        btClose.setText("X");
        btClose.setBorder(null);
        btClose.setContentAreaFilled(false);
        btClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCloseActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("ID");

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Profissão");

        btnCriar.setText("Criar");
        btnCriar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCriarActionPerformed(evt);
            }
        });

        btnAtualizar.setText("Atualizar");
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Pesquisar por ID");

        txtIDPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDPesquisarActionPerformed(evt);
            }
        });

        txtusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtusuarioActionPerformed(evt);
            }
        });

        btnEncontrar.setText("Encontrar");
        btnEncontrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEncontrarActionPerformed(evt);
            }
        });

        btnRelatorio.setText("Visualizar Perfil");
        btnRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelatorioActionPerformed(evt);
            }
        });

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Principal Habilidade");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btClose, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addComponent(btnCriar))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtProfissao, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(txtHabilidade, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addComponent(jLabel2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(btnAtualizar)
                                .addGap(18, 18, 18)
                                .addComponent(btnExcluir))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(txtIDPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEncontrar)
                        .addGap(33, 33, 33)
                        .addComponent(btnRelatorio))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel5)))
                .addContainerGap(186, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btClose)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(11, 11, 11)
                        .addComponent(txtHabilidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtProfissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtusuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCriar)
                    .addComponent(btnAtualizar)
                    .addComponent(btnExcluir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIDPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEncontrar)
                    .addComponent(btnRelatorio))
                .addContainerGap(89, Short.MAX_VALUE))
        );

        Tela_inicial_menu.setText("Tela inicial");
        Tela_inicial_menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tela_inicial_menuMouseClicked(evt);
            }
        });
        Barrademenu.add(Tela_inicial_menu);

        Projetos_menu.setText("Projetos");

        CriarProjetos.setText("Criar Projetos");
        CriarProjetos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CriarProjetosMouseClicked(evt);
            }
        });
        Projetos_menu.add(CriarProjetos);

        Barrademenu.add(Projetos_menu);

        Freelancers_menu.setText("Freelancers");
        Freelancers_menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Freelancers_menuMouseClicked(evt);
            }
        });

        criarPerfil.setText("Criar Perfil");
        criarPerfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                criarPerfilMouseClicked(evt);
            }
        });
        criarPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                criarPerfilActionPerformed(evt);
            }
        });
        Freelancers_menu.add(criarPerfil);

        Barrademenu.add(Freelancers_menu);

        Perfil_menu.setText("Perfil");
        Perfil_menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Perfil_menuMouseClicked(evt);
            }
        });
        Barrademenu.add(Perfil_menu);

        Ajuda_menu.setText("Ajuda");

        Admin_login.setText("Ajuda");
        Admin_login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Admin_loginMouseClicked(evt);
            }
        });
        Ajuda_menu.add(Admin_login);

        Barrademenu.add(Ajuda_menu);

        setJMenuBar(Barrademenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCloseActionPerformed
        dispose();
    }//GEN-LAST:event_btCloseActionPerformed

    private void btnCriarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCriarActionPerformed
        String profissao = txtProfissao.getText();
        int usuarioID = Integer.parseInt(txtusuario.getText());
        String habilidades = txtHabilidade.getText();

        Freelancer f = new Freelancer();
        f.setUsuarioID(usuarioID);
        f.setProfissao(profissao);
        f.setHabilidades(habilidades);
        
        FreelancerDAO freelancerDAO = new FreelancerDAO();
        freelancerDAO.inserir(f);
        
        txtusuario.setText("");
        txtProfissao.setText("");
        txtHabilidade.setText("");
    }//GEN-LAST:event_btnCriarActionPerformed

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
        int UsuarioID = Integer.parseInt(txtusuario.getText());
        String profissao = txtProfissao.getText();
        String habilidades = txtHabilidade.getText();
        Freelancer f = new Freelancer();
        f.setUsuarioID(UsuarioID);
        f.setProfissao(profissao);
        f.setHabilidades(habilidades);

        FreelancerDAO freelancerDAO = new FreelancerDAO();
        freelancerDAO.alterar(f);

        txtusuario.setText("");
        txtProfissao.setText("");
        txtHabilidade.setText("");
    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        int UsuarioID = Integer.parseInt(txtusuario.getText());
        FreelancerDAO freelancerDAO = new FreelancerDAO();
        freelancerDAO.excluir(UsuarioID);

        txtusuario.setText("");
        txtProfissao.setText("");
        txtHabilidade.setText("");
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void txtIDPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDPesquisarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDPesquisarActionPerformed

    private void txtusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtusuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtusuarioActionPerformed

    private void btnEncontrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEncontrarActionPerformed
        int idPesquisa = Integer.parseInt(txtIDPesquisar.getText());
        FreelancerDAO freelancerDAO = new FreelancerDAO();
        Freelancer f = freelancerDAO.getFreelancer(idPesquisa);
        if (f == null) {
            JOptionPane.showMessageDialog(this, "Produto não encontrado");
        } else {
            txtusuario.setText(String.valueOf(f.getUsuarioID()));
            txtProfissao.setText(f.getProfissao());
            txtHabilidade.setText(f.getHabilidades());
        }
    }//GEN-LAST:event_btnEncontrarActionPerformed

    private void btnRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelatorioActionPerformed
        Perfilview vrp = new Perfilview();
        vrp.setVisible(true);
    }//GEN-LAST:event_btnRelatorioActionPerformed

    private void btnGerenciarProjetosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerenciarProjetosActionPerformed
        
    }//GEN-LAST:event_btnGerenciarProjetosActionPerformed

    private void Tela_inicial_menuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tela_inicial_menuMouseClicked
        Main prin = new Main();
        this.dispose();  // Fecha a tela atual
        prin.setVisible(true);  // Abre a próxima tela
    }//GEN-LAST:event_Tela_inicial_menuMouseClicked

    private void CriarProjetosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CriarProjetosMouseClicked
        // TODO add your handling code here:
        projetoview prin = new projetoview();
        this.dispose();  // Fecha a tela atual
        prin.setVisible(true);  // Abre a próxima tela
    }//GEN-LAST:event_CriarProjetosMouseClicked

    private void criarPerfilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_criarPerfilMouseClicked
        freelancerview prin = new freelancerview();
        this.dispose();  // Fecha a tela atual
        prin.setVisible(true);  // Abre a próxima tela
    }//GEN-LAST:event_criarPerfilMouseClicked

    private void criarPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_criarPerfilActionPerformed
        // TODO add your handling code here:
        freelancerview prin = new freelancerview();
        this.dispose();  // Fecha a tela atual
        prin.setVisible(true);  // Abre a próxima tela
    }//GEN-LAST:event_criarPerfilActionPerformed

    private void Freelancers_menuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Freelancers_menuMouseClicked
        freelancerview prin = new freelancerview();
        this.dispose();  // Fecha a tela atual
        prin.setVisible(true);  // Abre a próxima tela
    }//GEN-LAST:event_Freelancers_menuMouseClicked

    private void Perfil_menuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Perfil_menuMouseClicked
        Perfilview vrp = new Perfilview();
        this.dispose();  // Fecha a tela atual
        vrp.setVisible(true);  // Abre a próxima tela
    }//GEN-LAST:event_Perfil_menuMouseClicked

    private void Admin_loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Admin_loginMouseClicked
        Admin_login prin = new Admin_login();
        this.dispose();  // Fecha a tela atual
        prin.setVisible(true);  // Abre a próxima tela
    }//GEN-LAST:event_Admin_loginMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new freelancerview().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Admin_login;
    private javax.swing.JMenu Ajuda_menu;
    private javax.swing.JMenuBar Barrademenu;
    private javax.swing.JMenu CriarProjetos;
    private javax.swing.JMenu Freelancers_menu;
    private javax.swing.JMenu Perfil_menu;
    private javax.swing.JMenu Projetos_menu;
    private javax.swing.JMenu Tela_inicial_menu;
    private javax.swing.JButton btClose;
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnCriar;
    private javax.swing.JButton btnEncontrar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnRelatorio;
    private javax.swing.JMenuItem criarPerfil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField txtHabilidade;
    private javax.swing.JTextField txtIDPesquisar;
    private javax.swing.JTextField txtProfissao;
    private javax.swing.JTextField txtusuario;
    // End of variables declaration//GEN-END:variables
}