/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

import javax.swing.JOptionPane;


/**
 *
 * @author gpont
 */
public class Login extends javax.swing.JFrame {

    

    /**
     * Creates new form NewJFrame
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Painel_principal = new javax.swing.JPanel();
        Painel_secundario = new javax.swing.JPanel();
        btClose = new javax.swing.JButton();
        Usuario_text = new javax.swing.JLabel();
        Senha_text = new javax.swing.JLabel();
        espaco_Senha = new javax.swing.JPasswordField();
        Usuario_espaco = new javax.swing.JTextField();
        senha_checkbox = new javax.swing.JCheckBox();
        btLogin = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();
        btCadastro = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);
        setResizable(false);

        Painel_principal.setBackground(new java.awt.Color(204, 204, 204));

        Painel_secundario.setBackground(new java.awt.Color(153, 153, 153));

        btClose.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        btClose.setForeground(new java.awt.Color(255, 0, 51));
        btClose.setText("X");
        btClose.setBorder(null);
        btClose.setContentAreaFilled(false);
        btClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Painel_secundarioLayout = new javax.swing.GroupLayout(Painel_secundario);
        Painel_secundario.setLayout(Painel_secundarioLayout);
        Painel_secundarioLayout.setHorizontalGroup(
            Painel_secundarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel_secundarioLayout.createSequentialGroup()
                .addGap(0, 319, Short.MAX_VALUE)
                .addComponent(btClose, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        Painel_secundarioLayout.setVerticalGroup(
            Painel_secundarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel_secundarioLayout.createSequentialGroup()
                .addComponent(btClose)
                .addContainerGap(521, Short.MAX_VALUE))
        );

        Usuario_text.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Usuario_text.setText("Usuario");

        Senha_text.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Senha_text.setText("Senha");

        espaco_Senha.setBackground(new java.awt.Color(153, 153, 153));
        espaco_Senha.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        espaco_Senha.setActionCommand("<Not Set>");
        espaco_Senha.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        espaco_Senha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                espaco_SenhaActionPerformed(evt);
            }
        });

        Usuario_espaco.setBackground(new java.awt.Color(153, 153, 153));
        Usuario_espaco.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Usuario_espaco.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        Usuario_espaco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Usuario_espacoActionPerformed(evt);
            }
        });

        senha_checkbox.setBackground(new java.awt.Color(204, 204, 204));
        senha_checkbox.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        senha_checkbox.setText(" Mostrar a senha");
        senha_checkbox.setToolTipText("");
        senha_checkbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                senha_checkboxActionPerformed(evt);
            }
        });

        btLogin.setBackground(new java.awt.Color(255, 0, 51));
        btLogin.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        btLogin.setText("Login");
        btLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLoginActionPerformed(evt);
            }
        });

        jLabel2.setText("saintlance 1.0");

        btCadastro.setBackground(new java.awt.Color(255, 0, 51));
        btCadastro.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        btCadastro.setText("Cadastro");
        btCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Painel_principalLayout = new javax.swing.GroupLayout(Painel_principal);
        Painel_principal.setLayout(Painel_principalLayout);
        Painel_principalLayout.setHorizontalGroup(
            Painel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel_principalLayout.createSequentialGroup()
                .addGroup(Painel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Painel_principalLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(Painel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Usuario_text)
                            .addGroup(Painel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(senha_checkbox, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(espaco_Senha, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Usuario_espaco, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Senha_text, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(Painel_principalLayout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(jLabel2))
                    .addGroup(Painel_principalLayout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(Painel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(61, 61, 61)
                .addComponent(Painel_secundario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Painel_principalLayout.setVerticalGroup(
            Painel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Painel_secundario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(Painel_principalLayout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(Usuario_text)
                .addGap(18, 18, 18)
                .addComponent(Usuario_espaco, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(Senha_text, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(espaco_Senha, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(senha_checkbox, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(btLogin)
                .addGap(18, 18, 18)
                .addComponent(btCadastro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Painel_principal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Painel_principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(688, 547));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void espaco_SenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_espaco_SenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_espaco_SenhaActionPerformed

    private void senha_checkboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_senha_checkboxActionPerformed
           // TODO add your handling code here:
    if(senha_checkbox.isSelected()){
            espaco_Senha.setEchoChar((char)0);
        }else{
            espaco_Senha.setEchoChar('*');
        }     
    }//GEN-LAST:event_senha_checkboxActionPerformed

    private void btCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCloseActionPerformed
        // TODO add your handling code here:
        dispose();
        
    }//GEN-LAST:event_btCloseActionPerformed

    private void Usuario_espacoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Usuario_espacoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Usuario_espacoActionPerformed

    private void btLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLoginActionPerformed
    String email = Usuario_espaco.getText();
    String senha = String.valueOf(espaco_Senha.getPassword());
    
    // Verificar se os campos não estão vazios
    if(email.isEmpty() || senha.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Por favor, preencha todos os campos.");
        return;
    }

    // Criar uma instância do LoginDAO
    dao.LoginDAO LoginDAO = new dao.LoginDAO();
    
    // Tentar autenticar o usuário
    beans.Usuario usuario = LoginDAO.autenticar(email, senha);
    
    // Verificar se o login foi bem-sucedido
    if (usuario != null) {
        // Sucesso no login
        JOptionPane.showMessageDialog(this, "Login bem-sucedido! Bem-vindo, " + usuario.getNome());
        
        Main prin = new Main();
        this.dispose();  // Fecha a tela de login
        prin.setVisible(true);  // Abre a próxima tela
        
    } else {
        // Falha no login
        JOptionPane.showMessageDialog(this, "Email ou senha incorretos. Tente novamente.");
    }
    }//GEN-LAST:event_btLoginActionPerformed

    private void btCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastroActionPerformed
        // TODO add your handling code here:
        Cadastro cad = new Cadastro();
        this.dispose();  // Fecha a tela de login
        cad.setVisible(true);  // Abre a próxima tela
    }//GEN-LAST:event_btCadastroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Painel_principal;
    private javax.swing.JPanel Painel_secundario;
    private javax.swing.JLabel Senha_text;
    private javax.swing.JTextField Usuario_espaco;
    private javax.swing.JLabel Usuario_text;
    private javax.swing.JToggleButton btCadastro;
    private javax.swing.JButton btClose;
    private javax.swing.JToggleButton btLogin;
    private javax.swing.JPasswordField espaco_Senha;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JCheckBox senha_checkbox;
    // End of variables declaration//GEN-END:variables
}
