/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import beans.Freelancer;
import dao.FreelancerDAO;
import java.util.List;
/**
 *
 * @author guilherme.pcampos3
 */
public class Perfilview extends javax.swing.JFrame {
private void preencherTabela(){
    FreelancerDAO freelancerDAO = new FreelancerDAO();
    List<Freelancer> listaFreelancer = freelancerDAO.getFreelance();
    DefaultTableModel tbperfil = (DefaultTableModel) jtperfil.getModel(); 
    
    for(Freelancer f : listaFreelancer){
        Object[] obj = new Object[]{
        f.getFreelancerID(),
        f.getProfissao(),
        f.getHabilidades()
        };
        tbperfil.addRow(obj);
    }
}
    /**
     * Creates new form Main
     */
    public Perfilview() {
        initComponents();
        preencherTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btClose = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtperfil = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        Barrademenu = new javax.swing.JMenuBar();
        Tela_inicial_menu = new javax.swing.JMenu();
        Projetos_menu = new javax.swing.JMenu();
        CriarProjetos = new javax.swing.JMenu();
        Freelancers_menu = new javax.swing.JMenu();
        criarPerfil = new javax.swing.JMenuItem();
        Perfil_menu = new javax.swing.JMenu();
        Ajuda_menu = new javax.swing.JMenu();
        Admin_login = new javax.swing.JMenu();

        jTextField1.setText("jTextField1");

        jLabel4.setBackground(new java.awt.Color(204, 204, 204));
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("PREÇO");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        btClose.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        btClose.setForeground(new java.awt.Color(255, 0, 51));
        btClose.setText("X");
        btClose.setBorder(null);
        btClose.setContentAreaFilled(false);
        btClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCloseActionPerformed(evt);
            }
        });

        jtperfil.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Id", "Profissao", "Habilidade"
            }
        ));
        jScrollPane1.setViewportView(jtperfil);

        jLabel1.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Perfil");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(236, 236, 236)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btClose, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 46, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel1))
                    .addComponent(btClose))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
        );

        Tela_inicial_menu.setText("Tela inicial");
        Tela_inicial_menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tela_inicial_menuMouseClicked(evt);
            }
        });
        Barrademenu.add(Tela_inicial_menu);

        Projetos_menu.setText("Projetos");

        CriarProjetos.setText("Criar Projetos");
        CriarProjetos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CriarProjetosMouseClicked(evt);
            }
        });
        Projetos_menu.add(CriarProjetos);

        Barrademenu.add(Projetos_menu);

        Freelancers_menu.setText("Freelancers");
        Freelancers_menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Freelancers_menuMouseClicked(evt);
            }
        });

        criarPerfil.setText("Criar Perfil");
        criarPerfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                criarPerfilMouseClicked(evt);
            }
        });
        criarPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                criarPerfilActionPerformed(evt);
            }
        });
        Freelancers_menu.add(criarPerfil);

        Barrademenu.add(Freelancers_menu);

        Perfil_menu.setText("Perfil");
        Perfil_menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Perfil_menuMouseClicked(evt);
            }
        });
        Barrademenu.add(Perfil_menu);

        Ajuda_menu.setText("Ajuda");

        Admin_login.setText("Ajuda");
        Admin_login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Admin_loginMouseClicked(evt);
            }
        });
        Ajuda_menu.add(Admin_login);

        Barrademenu.add(Ajuda_menu);

        setJMenuBar(Barrademenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCloseActionPerformed
        // TODO add your handling code here:
        dispose();

    }//GEN-LAST:event_btCloseActionPerformed

    private void Tela_inicial_menuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tela_inicial_menuMouseClicked
        Main prin = new Main();
        this.dispose();  // Fecha a tela atual
        prin.setVisible(true);  // Abre a próxima tela
    }//GEN-LAST:event_Tela_inicial_menuMouseClicked

    private void CriarProjetosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CriarProjetosMouseClicked
        // TODO add your handling code here:
        projetoview prin = new projetoview();
        this.dispose();  // Fecha a tela atual
        prin.setVisible(true);  // Abre a próxima tela
    }//GEN-LAST:event_CriarProjetosMouseClicked

    private void criarPerfilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_criarPerfilMouseClicked
        freelancerview prin = new freelancerview();
        this.dispose();  // Fecha a tela atual
        prin.setVisible(true);  // Abre a próxima tela
    }//GEN-LAST:event_criarPerfilMouseClicked

    private void criarPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_criarPerfilActionPerformed
        // TODO add your handling code here:
        freelancerview prin = new freelancerview();
        this.dispose();  // Fecha a tela atual
        prin.setVisible(true);  // Abre a próxima tela
    }//GEN-LAST:event_criarPerfilActionPerformed

    private void Freelancers_menuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Freelancers_menuMouseClicked
        freelancerview prin = new freelancerview();
        this.dispose();  // Fecha a tela atual
        prin.setVisible(true);  // Abre a próxima tela
    }//GEN-LAST:event_Freelancers_menuMouseClicked

    private void Perfil_menuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Perfil_menuMouseClicked
        Perfilview vrp = new Perfilview();
        this.dispose();  // Fecha a tela atual
        vrp.setVisible(true);  // Abre a próxima tela
    }//GEN-LAST:event_Perfil_menuMouseClicked

    private void Admin_loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Admin_loginMouseClicked
        Admin_login prin = new Admin_login();
        this.dispose();  // Fecha a tela atual
        prin.setVisible(true);  // Abre a próxima tela
    }//GEN-LAST:event_Admin_loginMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Perfilview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Perfilview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Perfilview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Perfilview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Perfilview().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Admin_login;
    private javax.swing.JMenu Ajuda_menu;
    private javax.swing.JMenuBar Barrademenu;
    private javax.swing.JMenu CriarProjetos;
    private javax.swing.JMenu Freelancers_menu;
    private javax.swing.JMenu Perfil_menu;
    private javax.swing.JMenu Projetos_menu;
    private javax.swing.JMenu Tela_inicial_menu;
    private javax.swing.JButton btClose;
    private javax.swing.JMenuItem criarPerfil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable jtperfil;
    // End of variables declaration//GEN-END:variables
}
