/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import beans.Projeto;
import dao.ProjetoDAO;

/**
 *
 * @author guilherme.pcampos3
 */
public class projetoview extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public projetoview() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btClose = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnCriar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        txtfreelancerID = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        txtDescricao = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtPreco = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtStatus = new javax.swing.JTextField();
        Barrademenu = new javax.swing.JMenuBar();
        Tela_inicial_menu = new javax.swing.JMenu();
        Projetos_menu = new javax.swing.JMenu();
        CriarProjetos = new javax.swing.JMenu();
        Freelancers_menu = new javax.swing.JMenu();
        criarPerfil = new javax.swing.JMenuItem();
        Perfil_menu = new javax.swing.JMenu();
        Ajuda_menu = new javax.swing.JMenu();
        Admin_login = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        btClose.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        btClose.setForeground(new java.awt.Color(255, 0, 51));
        btClose.setText("X");
        btClose.setBorder(null);
        btClose.setContentAreaFilled(false);
        btClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCloseActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("ID");

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Nome");

        btnCriar.setText("Criar");
        btnCriar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCriarActionPerformed(evt);
            }
        });

        txtfreelancerID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfreelancerIDActionPerformed(evt);
            }
        });

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Descrição");

        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Status");

        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Preço");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(59, 59, 59)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btClose, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(211, 211, 211))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtfreelancerID, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnCriar))
                .addContainerGap(91, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(txtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btClose)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2))
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtfreelancerID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCriar)
                .addGap(33, 33, 33))
        );

        Tela_inicial_menu.setText("Tela inicial");
        Tela_inicial_menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tela_inicial_menuMouseClicked(evt);
            }
        });
        Barrademenu.add(Tela_inicial_menu);

        Projetos_menu.setText("Projetos");

        CriarProjetos.setText("Criar Projetos");
        CriarProjetos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CriarProjetosMouseClicked(evt);
            }
        });
        Projetos_menu.add(CriarProjetos);

        Barrademenu.add(Projetos_menu);

        Freelancers_menu.setText("Freelancers");
        Freelancers_menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Freelancers_menuMouseClicked(evt);
            }
        });

        criarPerfil.setText("Criar Perfil");
        criarPerfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                criarPerfilMouseClicked(evt);
            }
        });
        criarPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                criarPerfilActionPerformed(evt);
            }
        });
        Freelancers_menu.add(criarPerfil);

        Barrademenu.add(Freelancers_menu);

        Perfil_menu.setText("Perfil");
        Perfil_menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Perfil_menuMouseClicked(evt);
            }
        });
        Barrademenu.add(Perfil_menu);

        Ajuda_menu.setText("Ajuda");

        Admin_login.setText("Ajuda");
        Admin_login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Admin_loginMouseClicked(evt);
            }
        });
        Ajuda_menu.add(Admin_login);

        Barrademenu.add(Ajuda_menu);

        setJMenuBar(Barrademenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCloseActionPerformed
        dispose();
    }//GEN-LAST:event_btCloseActionPerformed

    private void btnCriarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCriarActionPerformed
         int freelancerID = Integer.parseInt(txtfreelancerID.getText());
        String nome = txtNome.getText();
        String descricao = txtDescricao.getText();
        double preco =  Double.parseDouble(txtPreco.getText());
        String status = txtStatus.getText();

        Projeto f = new Projeto();
        f.setFreelancerID(freelancerID);
        f.setNome(nome);
        f.setDescricao(descricao);
        f.setPreco(preco);
        f.setStatus(status);
        
        ProjetoDAO projetoDAO = new ProjetoDAO();
        projetoDAO.inserir(f);
        
        txtfreelancerID.setText("");
        txtNome.setText("");
        txtPreco.setText("");
        txtDescricao.setText("");
        txtStatus.setText("");

        
    }//GEN-LAST:event_btnCriarActionPerformed

    private void txtfreelancerIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfreelancerIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfreelancerIDActionPerformed

    private void btnGerenciarProjetosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerenciarProjetosActionPerformed
        
    }//GEN-LAST:event_btnGerenciarProjetosActionPerformed

    private void Tela_inicial_menuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tela_inicial_menuMouseClicked
        Main prin = new Main();
        this.dispose();  // Fecha a tela atual
        prin.setVisible(true);  // Abre a próxima tela
    }//GEN-LAST:event_Tela_inicial_menuMouseClicked

    private void CriarProjetosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CriarProjetosMouseClicked
        // TODO add your handling code here:
        projetoview prin = new projetoview();
        this.dispose();  // Fecha a tela atual
        prin.setVisible(true);  // Abre a próxima tela
    }//GEN-LAST:event_CriarProjetosMouseClicked

    private void criarPerfilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_criarPerfilMouseClicked
        freelancerview prin = new freelancerview();
        this.dispose();  // Fecha a tela atual
        prin.setVisible(true);  // Abre a próxima tela
    }//GEN-LAST:event_criarPerfilMouseClicked

    private void criarPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_criarPerfilActionPerformed
        // TODO add your handling code here:
        freelancerview prin = new freelancerview();
        this.dispose();  // Fecha a tela atual
        prin.setVisible(true);  // Abre a próxima tela
    }//GEN-LAST:event_criarPerfilActionPerformed

    private void Freelancers_menuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Freelancers_menuMouseClicked
        freelancerview prin = new freelancerview();
        this.dispose();  // Fecha a tela atual
        prin.setVisible(true);  // Abre a próxima tela
    }//GEN-LAST:event_Freelancers_menuMouseClicked

    private void Perfil_menuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Perfil_menuMouseClicked
        Perfilview vrp = new Perfilview();
        this.dispose();  // Fecha a tela atual
        vrp.setVisible(true);  // Abre a próxima tela
    }//GEN-LAST:event_Perfil_menuMouseClicked

    private void Admin_loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Admin_loginMouseClicked
        Admin_login prin = new Admin_login();
        this.dispose();  // Fecha a tela atual
        prin.setVisible(true);  // Abre a próxima tela
    }//GEN-LAST:event_Admin_loginMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new projetoview().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Admin_login;
    private javax.swing.JMenu Ajuda_menu;
    private javax.swing.JMenuBar Barrademenu;
    private javax.swing.JMenu CriarProjetos;
    private javax.swing.JMenu Freelancers_menu;
    private javax.swing.JMenu Perfil_menu;
    private javax.swing.JMenu Projetos_menu;
    private javax.swing.JMenu Tela_inicial_menu;
    private javax.swing.JButton btClose;
    private javax.swing.JButton btnCriar;
    private javax.swing.JMenuItem criarPerfil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField txtDescricao;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtPreco;
    private javax.swing.JTextField txtStatus;
    private javax.swing.JTextField txtfreelancerID;
    // End of variables declaration//GEN-END:variables
}